### PR TITLE
Issue #86: Coins validation issues

### LINKED ISSUE #86: Coins validation issues
There are problems in the validation of the amount of coins in the send coins form. To solve it, please consult this pr and the associated issue: https://github.com/skycoin/skycoin/pull/1350.

### PR DESCRIPTION
**Pull request by alexandermushinskiy**
Fixes #86 

Changes:
- in send coin page: change validator for amount value, update reset form values
- new directive was created to allow specify only numbers

### CODE REVIEW

**Comment by alexandermushinskiy** [comment]
We switched from `type="number"` to `type="text"`, because number control can't validate numbers with big amount of digits as you mentioned in your previous post: 
> accepts values with more decimals than the maximum allowed (like 20.500000000000000001)
it's been rounded to 20 and that is why it validates as correct value.

**Comment by alexandermushinskiy** [comment]
As a proposition, we can switch back to `type="number"` and disable ability to specify more than 6 digits after decimal. What do you think?

**Comment by Senyoret1** [comment]
Let's do something: switch it back to `type="number"`, remove `NumberFieldDirective` from the input, and add a comment at the top of number-field.directive.ts with something like "Allows an input to accept only numbers. Currently, the paste option is failing, it needs some more testing". That way we keep the code for `NumberFieldDirective` (it would be a pity to delete it) and the final implementation could be reviewed with more detail in another pr, so I can merge this pr with more confidence. `validateAmount` is already responsible for preventing the user from continuing if the amount have more than 6 decimals.

**Comment by alexandermushinskiy** [comment]
@Senyoret1, we have switched back to `type="number"`.
Also have we updated copy-paste logic of NumberFieldDirective: it allows paste only if clipboard contains a number (can be decimal with dot), otherwise (if there is space, comma, letter, etc.) it prevents paste.

**Pull request merged**
