### PR TITLE
#205: Prod build error

### LINKED ISSUE #205: Prod build error
When using `npm run build` there are some compilation errors that must be fixed. In addition, `.travis.yml` must be modified so that Travis performs a production build as part of the tests it normally performs.

### PR DESCRIPTION
**Pull request by alexandermushinskiy**
Fixes #205 

Changes:
- update `transaction-info` component: show balance only if it's not preview;
- update `.travis.yaml`: add script to perform a production build.

### CODE REVIEW

**Comment by alexandermushinskiy** [comment]
@Senyoret1, yes, you are right, the error because Transaction class didn't have property `balance`.
The `balance` is not calculated when user wants to send coins: this field is not used neither `createTransaction()` nor `SendFormComponent`, so in preview it is undefined, isn't it?

**Comment by Senyoret1** [comment]
Indeed, it is a bit difficult to find and it looks like it should be undefined, but it is not, `balance` is assigned here:
https://github.com/skycoin/skycoin-web/blob/469f0406d487afef6775fcdb2e2958ad20caa67c/src/app/components/pages/send-skycoin/send-skycoin.component.ts#L25-L33

**Comment by alexandermushinskiy** [comment]
I need to fix my attentiveness urgently. It has been fixed.

**Comment by Senyoret1** [comment]
No problem, that happens sometimes :smile:

**Pull request merged**
